"""empty message

Revision ID: 123bbfd04917
Revises: e1167a66bf94
Create Date: 2025-02-03 20:05:00.516875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '123bbfd04917'
down_revision = 'e1167a66bf94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exercise_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_exercise_goals_exercise_id'), ['exercise_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exercise_goals_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(
            'fk_exercise_goals_exercise_id',  # Explicit foreign key name
            'exercises', ['exercise_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_foreign_key(
            'fk_exercise_goals_user_id',  # Explicit foreign key name
            'users', ['user_id'], ['id'], ondelete='CASCADE'
        )

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_goals', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exercise_goals_user_id'))
        batch_op.drop_index(batch_op.f('ix_exercise_goals_exercise_id'))
        batch_op.drop_column('user_id')
        batch_op.drop_column('exercise_id')

    # ### end Alembic commands ###
