"""empty message

Revision ID: 4cb223d55110
Revises: 24d0cc90bb61
Create Date: 2025-02-03 21:37:42.599507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb223d55110'
down_revision = '24d0cc90bb61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fitness_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('target_weight', sa.Float(), nullable=True),
    sa.Column('target_muscle_mass', sa.Float(), nullable=True),
    sa.Column('target_body_fat_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fitness_goals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fitness_goals_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_goals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fitness_goals_user_id'))

    op.drop_table('fitness_goals')
    # ### end Alembic commands ###
