"""empty message

Revision ID: 63b07593175e
Revises: 123bbfd04917
Create Date: 2025-02-03 21:23:24.231387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63b07593175e'
down_revision = '123bbfd04917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workout_session_exercises', schema=None) as batch_op:
        batch_op.drop_index('ix_workout_session_exercises_selected_exercise_id')
        batch_op.drop_index('ix_workout_session_exercises_workout_session_id')

    op.drop_table('workout_session_exercises')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workout_session_exercises',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('workout_session_id', sa.INTEGER(), nullable=False),
    sa.Column('selected_exercise_id', sa.INTEGER(), nullable=False),
    sa.Column('sets', sa.INTEGER(), nullable=True),
    sa.Column('reps', sa.INTEGER(), nullable=True),
    sa.Column('duration', sa.VARCHAR(length=50), nullable=True),
    sa.Column('distance', sa.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['selected_exercise_id'], ['selected_exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_session_id'], ['workout_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workout_session_exercises', schema=None) as batch_op:
        batch_op.create_index('ix_workout_session_exercises_workout_session_id', ['workout_session_id'], unique=False)
        batch_op.create_index('ix_workout_session_exercises_selected_exercise_id', ['selected_exercise_id'], unique=False)

    # ### end Alembic commands ###
